pub static MONSTER_FIRST_NAMES: [&str; 9] = [
    "rock",
    "ghost",
    "spirit",
    "zombie",
    "fire",
    "water",
    "ice",
    "dark",
    "lightning",
];

pub static MONSTER_LAST_NAMES: [&str; 17] = [
    "spider",
    "elemental",
    "skeleton",
    "diablo",
    "devil",
    "snake",
    "scavenger",
    "slime",
    "worm",
    "wurm",
    "wolf",
    "drake",
    "dragon",
    "basilisk",
    "toad",
    "beetle",
    "demon",
];
